// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/ritual_service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRitualsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRitualsRequest) Reset()         { *m = ListRitualsRequest{} }
func (m *ListRitualsRequest) String() string { return proto.CompactTextString(m) }
func (*ListRitualsRequest) ProtoMessage()    {}
func (*ListRitualsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_652c4c649de036fd, []int{0}
}

func (m *ListRitualsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRitualsRequest.Unmarshal(m, b)
}
func (m *ListRitualsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRitualsRequest.Marshal(b, m, deterministic)
}
func (m *ListRitualsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRitualsRequest.Merge(m, src)
}
func (m *ListRitualsRequest) XXX_Size() int {
	return xxx_messageInfo_ListRitualsRequest.Size(m)
}
func (m *ListRitualsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRitualsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRitualsRequest proto.InternalMessageInfo

func (m *ListRitualsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListRitualsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRitualsRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type ListRitualsResponse struct {
	Rituals              []*Ritual `protobuf:"bytes,1,rep,name=rituals,proto3" json:"rituals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListRitualsResponse) Reset()         { *m = ListRitualsResponse{} }
func (m *ListRitualsResponse) String() string { return proto.CompactTextString(m) }
func (*ListRitualsResponse) ProtoMessage()    {}
func (*ListRitualsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_652c4c649de036fd, []int{1}
}

func (m *ListRitualsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRitualsResponse.Unmarshal(m, b)
}
func (m *ListRitualsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRitualsResponse.Marshal(b, m, deterministic)
}
func (m *ListRitualsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRitualsResponse.Merge(m, src)
}
func (m *ListRitualsResponse) XXX_Size() int {
	return xxx_messageInfo_ListRitualsResponse.Size(m)
}
func (m *ListRitualsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRitualsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRitualsResponse proto.InternalMessageInfo

func (m *ListRitualsResponse) GetRituals() []*Ritual {
	if m != nil {
		return m.Rituals
	}
	return nil
}

type CreateRitualRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRitualRequest) Reset()         { *m = CreateRitualRequest{} }
func (m *CreateRitualRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRitualRequest) ProtoMessage()    {}
func (*CreateRitualRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_652c4c649de036fd, []int{2}
}

func (m *CreateRitualRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRitualRequest.Unmarshal(m, b)
}
func (m *CreateRitualRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRitualRequest.Marshal(b, m, deterministic)
}
func (m *CreateRitualRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRitualRequest.Merge(m, src)
}
func (m *CreateRitualRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRitualRequest.Size(m)
}
func (m *CreateRitualRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRitualRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRitualRequest proto.InternalMessageInfo

func (m *CreateRitualRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateRitualRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CreateRitualResponse struct {
	Ritual               *Ritual  `protobuf:"bytes,1,opt,name=ritual,proto3" json:"ritual,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRitualResponse) Reset()         { *m = CreateRitualResponse{} }
func (m *CreateRitualResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRitualResponse) ProtoMessage()    {}
func (*CreateRitualResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_652c4c649de036fd, []int{3}
}

func (m *CreateRitualResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRitualResponse.Unmarshal(m, b)
}
func (m *CreateRitualResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRitualResponse.Marshal(b, m, deterministic)
}
func (m *CreateRitualResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRitualResponse.Merge(m, src)
}
func (m *CreateRitualResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRitualResponse.Size(m)
}
func (m *CreateRitualResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRitualResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRitualResponse proto.InternalMessageInfo

func (m *CreateRitualResponse) GetRitual() *Ritual {
	if m != nil {
		return m.Ritual
	}
	return nil
}

type UpdateRitualRequest struct {
	Ritual               *Ritual  `protobuf:"bytes,1,opt,name=ritual,proto3" json:"ritual,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRitualRequest) Reset()         { *m = UpdateRitualRequest{} }
func (m *UpdateRitualRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRitualRequest) ProtoMessage()    {}
func (*UpdateRitualRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_652c4c649de036fd, []int{4}
}

func (m *UpdateRitualRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRitualRequest.Unmarshal(m, b)
}
func (m *UpdateRitualRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRitualRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRitualRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRitualRequest.Merge(m, src)
}
func (m *UpdateRitualRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRitualRequest.Size(m)
}
func (m *UpdateRitualRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRitualRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRitualRequest proto.InternalMessageInfo

func (m *UpdateRitualRequest) GetRitual() *Ritual {
	if m != nil {
		return m.Ritual
	}
	return nil
}

type UpdateRitualResponse struct {
	Ritual               *Ritual  `protobuf:"bytes,1,opt,name=ritual,proto3" json:"ritual,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRitualResponse) Reset()         { *m = UpdateRitualResponse{} }
func (m *UpdateRitualResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRitualResponse) ProtoMessage()    {}
func (*UpdateRitualResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_652c4c649de036fd, []int{5}
}

func (m *UpdateRitualResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRitualResponse.Unmarshal(m, b)
}
func (m *UpdateRitualResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRitualResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRitualResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRitualResponse.Merge(m, src)
}
func (m *UpdateRitualResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRitualResponse.Size(m)
}
func (m *UpdateRitualResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRitualResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRitualResponse proto.InternalMessageInfo

func (m *UpdateRitualResponse) GetRitual() *Ritual {
	if m != nil {
		return m.Ritual
	}
	return nil
}

type RitualSubscriptionRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RitualSubscriptionRequest) Reset()         { *m = RitualSubscriptionRequest{} }
func (m *RitualSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*RitualSubscriptionRequest) ProtoMessage()    {}
func (*RitualSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_652c4c649de036fd, []int{6}
}

func (m *RitualSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RitualSubscriptionRequest.Unmarshal(m, b)
}
func (m *RitualSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RitualSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *RitualSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RitualSubscriptionRequest.Merge(m, src)
}
func (m *RitualSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_RitualSubscriptionRequest.Size(m)
}
func (m *RitualSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RitualSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RitualSubscriptionRequest proto.InternalMessageInfo

func (m *RitualSubscriptionRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type RitualSubscriptionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RitualSubscriptionResponse) Reset()         { *m = RitualSubscriptionResponse{} }
func (m *RitualSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*RitualSubscriptionResponse) ProtoMessage()    {}
func (*RitualSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_652c4c649de036fd, []int{7}
}

func (m *RitualSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RitualSubscriptionResponse.Unmarshal(m, b)
}
func (m *RitualSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RitualSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *RitualSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RitualSubscriptionResponse.Merge(m, src)
}
func (m *RitualSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_RitualSubscriptionResponse.Size(m)
}
func (m *RitualSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RitualSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RitualSubscriptionResponse proto.InternalMessageInfo

type RitualUnsubscriptionRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RitualUnsubscriptionRequest) Reset()         { *m = RitualUnsubscriptionRequest{} }
func (m *RitualUnsubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*RitualUnsubscriptionRequest) ProtoMessage()    {}
func (*RitualUnsubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_652c4c649de036fd, []int{8}
}

func (m *RitualUnsubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RitualUnsubscriptionRequest.Unmarshal(m, b)
}
func (m *RitualUnsubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RitualUnsubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *RitualUnsubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RitualUnsubscriptionRequest.Merge(m, src)
}
func (m *RitualUnsubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_RitualUnsubscriptionRequest.Size(m)
}
func (m *RitualUnsubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RitualUnsubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RitualUnsubscriptionRequest proto.InternalMessageInfo

func (m *RitualUnsubscriptionRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type RitualUnsubscriptionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RitualUnsubscriptionResponse) Reset()         { *m = RitualUnsubscriptionResponse{} }
func (m *RitualUnsubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*RitualUnsubscriptionResponse) ProtoMessage()    {}
func (*RitualUnsubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_652c4c649de036fd, []int{9}
}

func (m *RitualUnsubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RitualUnsubscriptionResponse.Unmarshal(m, b)
}
func (m *RitualUnsubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RitualUnsubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *RitualUnsubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RitualUnsubscriptionResponse.Merge(m, src)
}
func (m *RitualUnsubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_RitualUnsubscriptionResponse.Size(m)
}
func (m *RitualUnsubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RitualUnsubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RitualUnsubscriptionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListRitualsRequest)(nil), "ritual.service.ListRitualsRequest")
	proto.RegisterType((*ListRitualsResponse)(nil), "ritual.service.ListRitualsResponse")
	proto.RegisterType((*CreateRitualRequest)(nil), "ritual.service.CreateRitualRequest")
	proto.RegisterType((*CreateRitualResponse)(nil), "ritual.service.CreateRitualResponse")
	proto.RegisterType((*UpdateRitualRequest)(nil), "ritual.service.UpdateRitualRequest")
	proto.RegisterType((*UpdateRitualResponse)(nil), "ritual.service.UpdateRitualResponse")
	proto.RegisterType((*RitualSubscriptionRequest)(nil), "ritual.service.RitualSubscriptionRequest")
	proto.RegisterType((*RitualSubscriptionResponse)(nil), "ritual.service.RitualSubscriptionResponse")
	proto.RegisterType((*RitualUnsubscriptionRequest)(nil), "ritual.service.RitualUnsubscriptionRequest")
	proto.RegisterType((*RitualUnsubscriptionResponse)(nil), "ritual.service.RitualUnsubscriptionResponse")
}

func init() { proto.RegisterFile("service/ritual_service.proto", fileDescriptor_652c4c649de036fd) }

var fileDescriptor_652c4c649de036fd = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xeb, 0xca, 0xd3, 0x40,
	0x10, 0xfd, 0xd2, 0x2b, 0x4e, 0xab, 0xe0, 0x26, 0x62, 0x8c, 0x45, 0xca, 0xea, 0x8f, 0x78, 0x69,
	0x52, 0x5b, 0xf1, 0x01, 0xd4, 0x0a, 0x82, 0xbf, 0xa2, 0x45, 0xf0, 0x42, 0xc9, 0x65, 0xa9, 0x8b,
	0xb9, 0xb9, 0xbb, 0x29, 0xf8, 0x0c, 0xbe, 0xb4, 0x34, 0xbb, 0x95, 0xc4, 0xa4, 0xb5, 0xfd, 0xfe,
	0x65, 0x66, 0xcf, 0x9c, 0x73, 0xc2, 0x1c, 0x06, 0x26, 0x9c, 0xb0, 0x1d, 0x0d, 0x89, 0xcb, 0xa8,
	0x28, 0xfc, 0x78, 0xa3, 0x4a, 0x27, 0x67, 0x99, 0xc8, 0xd0, 0x2d, 0xd9, 0x75, 0x54, 0xd7, 0xd2,
	0x93, 0x2c, 0x22, 0x31, 0x57, 0x60, 0x09, 0xc2, 0x9f, 0x00, 0xbd, 0xa7, 0x5c, 0x78, 0x65, 0x8f,
	0x7b, 0xe4, 0x67, 0x41, 0xb8, 0x40, 0x77, 0x61, 0x58, 0x70, 0xc2, 0x36, 0x34, 0x32, 0xb5, 0xa9,
	0x66, 0xdf, 0xf0, 0x06, 0xfb, 0xf2, 0x5d, 0x84, 0x0c, 0xe8, 0xc7, 0x34, 0xa1, 0xc2, 0xec, 0x4c,
	0x35, 0xbb, 0xeb, 0xc9, 0x02, 0x21, 0xe8, 0xe5, 0xfe, 0x96, 0x98, 0xdd, 0xb2, 0x59, 0x7e, 0xe3,
	0xb7, 0xa0, 0xd7, 0x88, 0x79, 0x9e, 0xa5, 0x9c, 0x20, 0x17, 0x86, 0x52, 0x9f, 0x9b, 0xda, 0xb4,
	0x6b, 0x8f, 0x16, 0x77, 0x1c, 0xe5, 0x47, 0xba, 0x73, 0xe4, 0x80, 0x77, 0x40, 0xe1, 0x37, 0xa0,
	0xbf, 0x66, 0xc4, 0x17, 0x44, 0x3d, 0x28, 0x87, 0x06, 0xf4, 0x05, 0x15, 0x31, 0x51, 0xfe, 0x64,
	0x51, 0xf5, 0xdd, 0xa9, 0xfa, 0xc6, 0x2b, 0x30, 0xea, 0x2c, 0xca, 0xce, 0x0c, 0x06, 0x52, 0xa8,
	0xe4, 0x39, 0xea, 0x46, 0x81, 0xf6, 0x66, 0xd6, 0x79, 0xd4, 0x30, 0x73, 0x21, 0xcb, 0x0a, 0x8c,
	0x3a, 0xcb, 0xf5, 0xcc, 0xbc, 0x80, 0x7b, 0xb2, 0xf3, 0xa1, 0x08, 0x78, 0xc8, 0x68, 0x2e, 0x68,
	0x96, 0xfe, 0x6f, 0x83, 0x78, 0x02, 0x56, 0xdb, 0x94, 0xb4, 0x80, 0x5f, 0xc2, 0x7d, 0xf9, 0xba,
	0x4e, 0xf9, 0x25, 0xac, 0x0f, 0x60, 0xd2, 0x3e, 0x27, 0x79, 0x17, 0xbf, 0x7b, 0x70, 0x53, 0xc9,
	0xca, 0x34, 0xa2, 0xaf, 0x30, 0xaa, 0xe4, 0x03, 0x61, 0xa7, 0x9e, 0x56, 0xa7, 0x99, 0x4a, 0xeb,
	0xe1, 0x49, 0x8c, 0xfa, 0x83, 0x2b, 0x5b, 0x9b, 0x6b, 0xe8, 0x1b, 0x8c, 0xab, 0xfb, 0x46, 0x8d,
	0xd1, 0x96, 0x4c, 0x59, 0x8f, 0x4e, 0x83, 0x0e, 0x02, 0x73, 0x0d, 0x7d, 0x81, 0x71, 0x75, 0x83,
	0x4d, 0xfa, 0x96, 0x94, 0x34, 0xe9, 0xdb, 0x42, 0x80, 0xaf, 0x50, 0x0c, 0xb7, 0xd5, 0x6e, 0x02,
	0xf2, 0x31, 0x53, 0x0a, 0x8f, 0xff, 0x1d, 0x3e, 0xba, 0x7a, 0xeb, 0xc9, 0x39, 0xd0, 0xbf, 0x6a,
	0x0c, 0xf4, 0x75, 0xda, 0xd4, 0x7b, 0xda, 0x4e, 0xd2, 0x1a, 0x0b, 0xeb, 0xd9, 0x79, 0xe0, 0x83,
	0xe6, 0xab, 0xe5, 0xe7, 0xe7, 0x5b, 0x2a, 0xbe, 0x17, 0x81, 0x13, 0x66, 0x89, 0xeb, 0x8b, 0x5f,
	0x39, 0x0d, 0xfd, 0x38, 0x22, 0x3b, 0x75, 0x9b, 0x66, 0x89, 0xff, 0x83, 0x30, 0xb7, 0xbc, 0x50,
	0xae, 0xe2, 0x0c, 0x06, 0x65, 0xb9, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x65, 0xd2, 0x19,
	0xf5, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RitualServiceClient is the client API for RitualService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RitualServiceClient interface {
	ListRituals(ctx context.Context, opts ...grpc.CallOption) (RitualService_ListRitualsClient, error)
	CreateRitual(ctx context.Context, in *CreateRitualRequest, opts ...grpc.CallOption) (RitualService_CreateRitualClient, error)
	UpdateRitual(ctx context.Context, in *UpdateRitualRequest, opts ...grpc.CallOption) (*UpdateRitualResponse, error)
	SubscribeToRitual(ctx context.Context, in *RitualSubscriptionRequest, opts ...grpc.CallOption) (*RitualSubscriptionResponse, error)
	UnSubscribeToRitual(ctx context.Context, in *RitualUnsubscriptionRequest, opts ...grpc.CallOption) (*RitualUnsubscriptionResponse, error)
}

type ritualServiceClient struct {
	cc *grpc.ClientConn
}

func NewRitualServiceClient(cc *grpc.ClientConn) RitualServiceClient {
	return &ritualServiceClient{cc}
}

func (c *ritualServiceClient) ListRituals(ctx context.Context, opts ...grpc.CallOption) (RitualService_ListRitualsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RitualService_serviceDesc.Streams[0], "/ritual.service.RitualService/ListRituals", opts...)
	if err != nil {
		return nil, err
	}
	x := &ritualServiceListRitualsClient{stream}
	return x, nil
}

type RitualService_ListRitualsClient interface {
	Send(*ListRitualsRequest) error
	Recv() (*ListRitualsResponse, error)
	grpc.ClientStream
}

type ritualServiceListRitualsClient struct {
	grpc.ClientStream
}

func (x *ritualServiceListRitualsClient) Send(m *ListRitualsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ritualServiceListRitualsClient) Recv() (*ListRitualsResponse, error) {
	m := new(ListRitualsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ritualServiceClient) CreateRitual(ctx context.Context, in *CreateRitualRequest, opts ...grpc.CallOption) (RitualService_CreateRitualClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RitualService_serviceDesc.Streams[1], "/ritual.service.RitualService/CreateRitual", opts...)
	if err != nil {
		return nil, err
	}
	x := &ritualServiceCreateRitualClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RitualService_CreateRitualClient interface {
	Recv() (*CreateRitualResponse, error)
	grpc.ClientStream
}

type ritualServiceCreateRitualClient struct {
	grpc.ClientStream
}

func (x *ritualServiceCreateRitualClient) Recv() (*CreateRitualResponse, error) {
	m := new(CreateRitualResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ritualServiceClient) UpdateRitual(ctx context.Context, in *UpdateRitualRequest, opts ...grpc.CallOption) (*UpdateRitualResponse, error) {
	out := new(UpdateRitualResponse)
	err := c.cc.Invoke(ctx, "/ritual.service.RitualService/UpdateRitual", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ritualServiceClient) SubscribeToRitual(ctx context.Context, in *RitualSubscriptionRequest, opts ...grpc.CallOption) (*RitualSubscriptionResponse, error) {
	out := new(RitualSubscriptionResponse)
	err := c.cc.Invoke(ctx, "/ritual.service.RitualService/SubscribeToRitual", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ritualServiceClient) UnSubscribeToRitual(ctx context.Context, in *RitualUnsubscriptionRequest, opts ...grpc.CallOption) (*RitualUnsubscriptionResponse, error) {
	out := new(RitualUnsubscriptionResponse)
	err := c.cc.Invoke(ctx, "/ritual.service.RitualService/UnSubscribeToRitual", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RitualServiceServer is the server API for RitualService service.
type RitualServiceServer interface {
	ListRituals(RitualService_ListRitualsServer) error
	CreateRitual(*CreateRitualRequest, RitualService_CreateRitualServer) error
	UpdateRitual(context.Context, *UpdateRitualRequest) (*UpdateRitualResponse, error)
	SubscribeToRitual(context.Context, *RitualSubscriptionRequest) (*RitualSubscriptionResponse, error)
	UnSubscribeToRitual(context.Context, *RitualUnsubscriptionRequest) (*RitualUnsubscriptionResponse, error)
}

// UnimplementedRitualServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRitualServiceServer struct {
}

func (*UnimplementedRitualServiceServer) ListRituals(srv RitualService_ListRitualsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListRituals not implemented")
}
func (*UnimplementedRitualServiceServer) CreateRitual(req *CreateRitualRequest, srv RitualService_CreateRitualServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateRitual not implemented")
}
func (*UnimplementedRitualServiceServer) UpdateRitual(ctx context.Context, req *UpdateRitualRequest) (*UpdateRitualResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRitual not implemented")
}
func (*UnimplementedRitualServiceServer) SubscribeToRitual(ctx context.Context, req *RitualSubscriptionRequest) (*RitualSubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscribeToRitual not implemented")
}
func (*UnimplementedRitualServiceServer) UnSubscribeToRitual(ctx context.Context, req *RitualUnsubscriptionRequest) (*RitualUnsubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnSubscribeToRitual not implemented")
}

func RegisterRitualServiceServer(s *grpc.Server, srv RitualServiceServer) {
	s.RegisterService(&_RitualService_serviceDesc, srv)
}

func _RitualService_ListRituals_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RitualServiceServer).ListRituals(&ritualServiceListRitualsServer{stream})
}

type RitualService_ListRitualsServer interface {
	Send(*ListRitualsResponse) error
	Recv() (*ListRitualsRequest, error)
	grpc.ServerStream
}

type ritualServiceListRitualsServer struct {
	grpc.ServerStream
}

func (x *ritualServiceListRitualsServer) Send(m *ListRitualsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ritualServiceListRitualsServer) Recv() (*ListRitualsRequest, error) {
	m := new(ListRitualsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RitualService_CreateRitual_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateRitualRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RitualServiceServer).CreateRitual(m, &ritualServiceCreateRitualServer{stream})
}

type RitualService_CreateRitualServer interface {
	Send(*CreateRitualResponse) error
	grpc.ServerStream
}

type ritualServiceCreateRitualServer struct {
	grpc.ServerStream
}

func (x *ritualServiceCreateRitualServer) Send(m *CreateRitualResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _RitualService_UpdateRitual_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRitualRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RitualServiceServer).UpdateRitual(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ritual.service.RitualService/UpdateRitual",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RitualServiceServer).UpdateRitual(ctx, req.(*UpdateRitualRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RitualService_SubscribeToRitual_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RitualSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RitualServiceServer).SubscribeToRitual(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ritual.service.RitualService/SubscribeToRitual",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RitualServiceServer).SubscribeToRitual(ctx, req.(*RitualSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RitualService_UnSubscribeToRitual_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RitualUnsubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RitualServiceServer).UnSubscribeToRitual(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ritual.service.RitualService/UnSubscribeToRitual",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RitualServiceServer).UnSubscribeToRitual(ctx, req.(*RitualUnsubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RitualService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ritual.service.RitualService",
	HandlerType: (*RitualServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateRitual",
			Handler:    _RitualService_UpdateRitual_Handler,
		},
		{
			MethodName: "SubscribeToRitual",
			Handler:    _RitualService_SubscribeToRitual_Handler,
		},
		{
			MethodName: "UnSubscribeToRitual",
			Handler:    _RitualService_UnSubscribeToRitual_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListRituals",
			Handler:       _RitualService_ListRituals_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateRitual",
			Handler:       _RitualService_CreateRitual_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service/ritual_service.proto",
}
