// Code generated by protoc-gen-go. DO NOT EDIT.
// source: models/ritual.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ritual struct {
	// Id of the ritual
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Id of the user that created the ritual
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Title of the ritual
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// List of RitualSteps for the Ritual
	Steps                []*RitualStep `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Ritual) Reset()         { *m = Ritual{} }
func (m *Ritual) String() string { return proto.CompactTextString(m) }
func (*Ritual) ProtoMessage()    {}
func (*Ritual) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ed4337e61ba1ef4, []int{0}
}

func (m *Ritual) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ritual.Unmarshal(m, b)
}
func (m *Ritual) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ritual.Marshal(b, m, deterministic)
}
func (m *Ritual) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ritual.Merge(m, src)
}
func (m *Ritual) XXX_Size() int {
	return xxx_messageInfo_Ritual.Size(m)
}
func (m *Ritual) XXX_DiscardUnknown() {
	xxx_messageInfo_Ritual.DiscardUnknown(m)
}

var xxx_messageInfo_Ritual proto.InternalMessageInfo

func (m *Ritual) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Ritual) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Ritual) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Ritual) GetSteps() []*RitualStep {
	if m != nil {
		return m.Steps
	}
	return nil
}

type RitualStep struct {
	// The instructions for a given ritual Step
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Marks the RitualStep as completed or not
	Completed bool `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	// Lays out the estimated minutes for the given ritual step.
	EstimatedMinutes     int64    `protobuf:"varint,3,opt,name=estimated_minutes,json=estimatedMinutes,proto3" json:"estimated_minutes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RitualStep) Reset()         { *m = RitualStep{} }
func (m *RitualStep) String() string { return proto.CompactTextString(m) }
func (*RitualStep) ProtoMessage()    {}
func (*RitualStep) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ed4337e61ba1ef4, []int{1}
}

func (m *RitualStep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RitualStep.Unmarshal(m, b)
}
func (m *RitualStep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RitualStep.Marshal(b, m, deterministic)
}
func (m *RitualStep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RitualStep.Merge(m, src)
}
func (m *RitualStep) XXX_Size() int {
	return xxx_messageInfo_RitualStep.Size(m)
}
func (m *RitualStep) XXX_DiscardUnknown() {
	xxx_messageInfo_RitualStep.DiscardUnknown(m)
}

var xxx_messageInfo_RitualStep proto.InternalMessageInfo

func (m *RitualStep) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RitualStep) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *RitualStep) GetEstimatedMinutes() int64 {
	if m != nil {
		return m.EstimatedMinutes
	}
	return 0
}

func init() {
	proto.RegisterType((*Ritual)(nil), "ritual.models.Ritual")
	proto.RegisterType((*RitualStep)(nil), "ritual.models.RitualStep")
}

func init() { proto.RegisterFile("models/ritual.proto", fileDescriptor_4ed4337e61ba1ef4) }

var fileDescriptor_4ed4337e61ba1ef4 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x69, 0xd7, 0xae, 0x76, 0x8a, 0xa2, 0x51, 0x70, 0x05, 0x0f, 0x4b, 0x4f, 0x05, 0x71,
	0x83, 0xfa, 0x0f, 0xbc, 0x79, 0xf0, 0x12, 0x6f, 0x5e, 0x4a, 0xba, 0x19, 0x74, 0x30, 0x69, 0x42,
	0x32, 0x2b, 0xf6, 0xdf, 0x8b, 0xc9, 0x62, 0xf5, 0xf8, 0x7d, 0x13, 0x78, 0x2f, 0x0f, 0xce, 0x9d,
	0x37, 0x68, 0x93, 0x8c, 0xc4, 0x83, 0xb6, 0x5d, 0x88, 0x9e, 0xbd, 0x38, 0x1e, 0xa9, 0xdc, 0x96,
	0x5f, 0x50, 0xab, 0x2c, 0xc4, 0x09, 0x4c, 0xc9, 0x34, 0x93, 0x76, 0xb2, 0x9a, 0xab, 0x29, 0x19,
	0x71, 0x09, 0x87, 0x43, 0xc2, 0xb8, 0x26, 0xd3, 0x4c, 0xb3, 0xac, 0x7f, 0xf0, 0xc9, 0x88, 0x0b,
	0x98, 0x31, 0xb1, 0xc5, 0xa6, 0xca, 0xba, 0x80, 0x90, 0x30, 0x4b, 0x8c, 0x21, 0x35, 0x07, 0x6d,
	0xb5, 0x5a, 0xdc, 0x5f, 0x75, 0xff, 0x72, 0xba, 0x12, 0xf2, 0xc2, 0x18, 0x54, 0x79, 0xb7, 0xdc,
	0x01, 0xec, 0xa5, 0x68, 0x61, 0x61, 0x30, 0xf5, 0x91, 0x02, 0x93, 0xdf, 0x8e, 0x35, 0xfe, 0x2a,
	0x71, 0x0d, 0xf3, 0xde, 0xbb, 0x60, 0x91, 0xb1, 0x34, 0x3a, 0x52, 0x7b, 0x21, 0x6e, 0xe0, 0x0c,
	0x13, 0x93, 0xd3, 0x8c, 0x66, 0xed, 0x68, 0x3b, 0x30, 0xa6, 0x5c, 0xb0, 0x52, 0xa7, 0xbf, 0x87,
	0xe7, 0xe2, 0x1f, 0xef, 0x5e, 0xe5, 0x1b, 0xf1, 0xfb, 0xb0, 0xe9, 0x7a, 0xef, 0xa4, 0xe6, 0x5d,
	0xa0, 0x5e, 0x5b, 0x83, 0x9f, 0xe3, 0x54, 0xb7, 0x4e, 0x7f, 0x60, 0x94, 0x79, 0x30, 0x99, 0x3f,
	0xb0, 0xa9, 0x33, 0x3c, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0x07, 0xae, 0x91, 0xa8, 0x54, 0x01,
	0x00, 0x00,
}
